s = set()
n = int(input("Enter number 1: "))
s.add(n)
n = int(input("Enter number 1: "))
s.add(n)
n = int(input("Enter number 1: "))
s.add(n)
n = int(input("Enter number 1: "))
s.add(n)
n = int(input("Enter number 1: "))
s.add(n)
n = int(input("Enter number 1: "))
s.add(n)
n = int(input("Enter number 1: "))
s.add(n)

print(s)

